title: Club Up
description: Club directory for students to search for clubs and link up with like-minded individuals. The link to our Github Organization is below.
google_analytics:
show_downloads: false
theme: jekyll-theme-minimal
gems:
  - jekyll-mentions
