title: Club Meetup
description: Club directory for students to search for clubs and link up with like-minded invididuals
table of contents: Overview
google_analytics:
show_downloads: true
theme: jekyll-theme-minimal
gems:
  - jekyll-mentions
